name: Build and Push Docker image to GCP

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      STACK: ${{ vars.STACK }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Google Cloud Authentication
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker to use gcloud
        run: |
          gcloud auth configure-docker
          
      - name: Build and Push Django Docker image to GCP
        run: |
          IMAGE_NAME=gcr.io/deploy-box/${{ env.STACK }}
          docker build -t $IMAGE_NAME source_code
          docker push $IMAGE_NAME